import type { Metadata } from "next";
import "./globals.css";
import { ProvidersWrapper } from "components/ui/providers/ProvidersWrapper";
import NavBar from "components/ui/components/sections/NavBar/NavBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="overflow-hidden">
        <ProvidersWrapper>
          <NavBar />
          <main className="flex-1 overflow-auto h-screen p-6 max-h-screen">
            <div className="">{children}</div>
          </main>
        </ProvidersWrapper>
      </body>
    </html>
  );
}
